language: node_js

sudo: false

node_js:
  - "8"

env:
- NODE_VERSION=8
- NODE_VERSION=10
- NODE_VERSION=12.13.0

cache:
  directories:
    - node_module

script:
  - npm run build
  - npm run clean
  - npm test

after_success: npm run coverage

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $NODE_VERSION = 12.13.0 && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      repo: laurelnaiad/dtsintergen
    email: laurelnaiad@gmail.com
    api_key:
      secure: guurnQHJxBaZS+fe5YKNYXTUHqdDL6BLk4ETPtv7OmzJeVAmwgSMO4adaYR+5RpEEH52Dj8i0fXSz62bZXT0NJD7zv4/HdfM+aZmuGC9l0eOsEg6XyMfYo6tiQRcPX2PUq5fnGciXIji0xMLbuwcNQ+Cp6svoQDKDR4LQjhxCJdG9osWyWcqjfLYxvzUqAJmzgoN/WJRFUYSm+W7K+h9dZ0EKSKgPrVYQqaKtaCSnjMyIuAYjPaDexRT/3lefLnJ9BuYW849YnqNnh2l8R5L9aBqgs6KdQRrcxOww5g00Oa/De2OPbAxQU0yW4dLun+bIDlKZshWDqbFhXarBXvah2fDbLVtx4ePYxz7AkPZGZisDm+upmQRL3JL2NhSATnSxiW11vDIjprU62EP7Cn97mrDMD0M/zZUfzrtoMpR8tKIE2rEs3PXVnnX+zZD3lCjMNJLLXy0IwdckerrBqE1dJsW9/qTLlSg7VezIDRlqKVhV2WuzIUAluGR+em/Aht5S5X3yMIoqQvxJAqx3UckJwsLN09QZs3u2PvdBcae995w3Tui8cfPUaCS5ju90qQxrs4PB9Izb2RWxkHE3Ixgfgn8LM36Wnz+KslNt6xD3fIk6B2ZWEzdwQLJqFhujzVTvwFUZlo/CttqupQdO4MzjpxLrBwFfQ5i2UPa8NR30LY=
